name: Generate Allure Report (Manual)

on:
  workflow_dispatch:   # Manual trigger only

jobs:
  allure-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Install Node & Dependencies
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 24.x

    - name: Install Dependencies
      run: npm ci

    # Run Playwright Tests to generate allure-results
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright Tests
      run: npx playwright test

    # Restore previous history from gh-pages (for trend graph)
    - name: Download Allure History
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true

    - name: Copy Allure History
      run: |
        mkdir -p allure-history
        if [ -d "gh-pages/allure-history" ]; then
          cp -r gh-pages/allure-history/* allure-history/ || true
        fi

    # Install Allure CLI
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    # Generate Allure Report
    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report
        cp -r allure-report/history allure-history || true
        cp -r allure-history allure-report

    # Deploy to GitHub Pages (Private)
    - name: Deploy Allure Report to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages
