name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 24.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    # ---------- SAVE HISTORY (IMPORTANT FOR GRAPH) ----------
    - name: Download Allure History
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
      continue-on-error: true

    - name: Copy Allure History
      run: |
        mkdir -p allure-history
        if [ -d "gh-pages" ]; then
          cp -r gh-pages/allure-history/* allure-history/ || true
        fi

    # ---------- GENERATE ALLURE HTML REPORT ----------
    - name: Generate Allure Report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate allure-results --clean -o allure-report
        cp -r allure-report/history allure-history || true
        cp -r allure-history allure-report

    # ---------- DEPLOY REPORT TO GITHUB PAGES ----------
    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report

