name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: 24.x
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      env:
        BASE_URL: ${{ secrets.BASE_URL || 'https://www.yesmadam.com' }}
        NODE_ENV: production
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      env:
        BASE_URL: ${{ secrets.BASE_URL || 'https://www.yesmadam.com' }}
        NODE_ENV: production
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_TO: ${{ secrets.EMAIL_TO }}
        EMAIL_SUBJECT: ${{ secrets.EMAIL_SUBJECT }}

    # Generate Allure Report
    - name: Install Allure CLI
      run: npm install -g allure-commandline --save-dev

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report
        cp -r allure-report/history allure-history || true
        cp -r allure-history allure-report
      env:
        BASE_URL: ${{ secrets.BASE_URL || 'https://www.yesmadam.com' }}
        NODE_ENV: production

    # Upload test results
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    # Upload Allure results
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results
        path: allure-results/
        retention-days: 30

    # Deploy Allure Report to GitHub Pages
    - name: Deploy Allure Report to gh-pages
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report
        publish_branch: gh-pages




